services:
    flasher.noty:
        parent: 'flasher.abstract_factory'
        class: Flasher\Noty\Prime\NotyFactory
        tags:
            - { name: 'flasher.factory', alias: 'noty' }

    Flasher\Noty\Prime\NotyFactory: '@flasher.noty'
