services:
    flasher.event_dispatcher:
        class: Flasher\Prime\EventDispatcher\EventDispatcher

    Flasher\Prime\EventDispatcher\EventListener\PostFilterListener:
        public: false
        tags:
            - 'flasher.event_subscriber'

    Flasher\Prime\EventDispatcher\EventListener\PostFlushListener:
        public: false
        arguments:
            - '@flasher.storage'
        tags:
            - 'flasher.event_subscriber'

    Flasher\Prime\EventDispatcher\EventListener\MiddlewareListener:
        public: false
        arguments:
            - '@flasher.flasher_bus'
        tags:
            - 'flasher.event_subscriber'

    Flasher\Prime\EventDispatcher\EventListener\StorageListener:
        public: false
        arguments:
            - '@flasher.storage'
        tags:
            - 'flasher.event_subscriber'
