services:
    flasher.flasher_bus:
        class: Flasher\Prime\Middleware\FlasherBus

    Flasher\Prime\Middleware\AddCreatedAtStampMiddleware:
        public: false
        tags:
            - 'flasher.middleware'

    Flasher\Prime\Middleware\AddHopsStampMiddleware:
        public: false
        tags:
            - 'flasher.middleware'

    Flasher\Prime\Middleware\AddPriorityStampMiddleware:
        public: false
        tags:
            - 'flasher.middleware'

    Flasher\Prime\Middleware\AddRenderedAtStampMiddleware:
        public: false
        tags:
            - 'flasher.middleware'
