services:
    flasher.presenter_manager:
        class: Flasher\Prime\Presenter\PresenterManager
        parent: 'flasher.abstract_manager'

    flasher.abstract_presenter:
        class: Flasher\Prime\Presenter\AbstractPresenter
        abstract: true
        arguments:
            - '@flasher.event_dispatcher'
            - '@flasher.config'
            - '@flasher.storage_manager'
            - '@flasher.filter_manager'
            - '@flasher.renderer_manager'

    flasher.presenter.html:
        class: Flasher\Prime\Presenter\Adapter\HtmlPresenter
        parent: 'flasher.abstract_presenter'
        tags:
            - 'flasher.presenter'

    flasher.presenter.json:
        class: Flasher\Prime\Presenter\Adapter\JsonPresenter
        parent: 'flasher.abstract_presenter'
        tags:
            - 'flasher.presenter'
