services:
    flasher.factory.notyf:
        parent: 'flasher.factory.abstract'
        class: Flasher\Notyf\Prime\Factory\NotyfProducer
        tags:
            - { name: 'flasher.factory', alias: 'notyf' }

    flasher.renderer.notyf:
        class: Flasher\Notyf\Prime\Renderer\NotyfRenderer
        arguments:
            - '@flasher.config'
        tags:
            - { name: 'flasher.renderer', alias: 'notyf' }

    Flasher\Notyf\Prime\Factory\NotyfProducer: '@flasher.factory.notyf'
    Flasher\Notyf\Prime\Renderer\NotyfRenderer: '@flasher.renderer.notyf'
