services:
    flasher.toastr:
        parent: 'flasher.abstract_factory'
        class: Flasher\Toastr\Prime\ToastrFactory
        tags:
            - { name: 'flasher.factory', alias: 'toastr' }

    Flasher\Toastr\Prime\ToastrFactory: '@flasher.toastr'
