services:
    flasher.factory.sweet_alert:
        parent: 'flasher.factory.abstract'
        class: Flasher\SweetAlert\Prime\Factory\SweetAlertProducer
        tags:
            - { name: 'flasher.factory', alias: 'sweet_alert' }

    flasher.renderer.sweet_alert:
        class: Flasher\SweetAlert\Prime\Renderer\SweetAlertRenderer
        arguments:
            - '@flasher.config'
        tags:
            - { name: 'flasher.renderer', alias: 'sweet_alert' }

    Flasher\SweetAlert\Prime\Factory\SweetAlertProducer: '@flasher.factory.sweet_alert'
    Flasher\SweetAlert\Prime\Renderer\SweetAlertRenderer: '@flasher.renderer.sweet_alert'
