services:
    flasher.factory.sweet_alert:
        parent: 'flasher.factory.abstract'
        class: Flasher\SweetAlert\Prime\SweetAlertFactory
        tags:
            - { name: 'flasher.factory' }

    flasher.renderer.sweet_alert:
        class: Flasher\SweetAlert\Prime\SweetAlertRenderer
        arguments:
            - '@flasher.config'
        tags:
            - { name: 'flasher.renderer' }

    Flasher\SweetAlert\Prime\SweetAlertFactory: '@flasher.factory.sweet_alert'
    Flasher\SweetAlert\Prime\SweetAlertRenderer: '@flasher.renderer.sweet_alert'
