services:
    flasher.notyf:
        parent: 'flasher.abstract_factory'
        class: Flasher\Notyf\Prime\NotyfFactory
        tags:
            - { name: 'flasher.factory', alias: 'notyf' }

    Flasher\Notyf\Prime\NotyfFactory: '@flasher.notyf'
