services:
    flasher.factory.pnotify:
        parent: 'flasher.factory.abstract'
        class: Flasher\PFlasher\Prime\TestsProducer\PnotifyProducer
        tags:
            - { name: 'flasher.factory', alias: 'pnotify' }

    flasher.renderer.pnotify:
        class: Flasher\PFlasher\Prime\Renderer\PnotifyRenderer
        arguments:
            - '@flasher.config'
        tags:
            - { name: 'flasher.renderer', alias: 'pnotify' }

    Flasher\PFlasher\Prime\TestsProducer\PnotifyProducer: '@flasher.factory.pnotify'
    Flasher\PFlasher\Prime\Renderer\PnotifyRenderer: '@flasher.renderer.pnotify'
