services:
    Flasher\Prime\Config\Config: '@flasher.config'
    Flasher\Prime\Manager\AbstractManager: '@flasher.abstract_manager'
    Flasher\Prime\Flasher: '@flasher'
    Flasher\Prime\Presenter\PresenterManager: '@flasher.presenter_manager'
    Flasher\Prime\Renderer\RendererManager: '@flasher.renderer_manager'
    Flasher\Prime\Middleware\FlasherBus: '@flasher.flasher_bus'
    Flasher\Prime\EventDispatcher\EventDispatcher: '@flasher.event_dispatcher'
    Flasher\Symfony\Storage\Storage: '@flasher.storage'
    Flasher\Prime\Storage\StorageManager: '@flasher.storage_manager'
    Flasher\Prime\Filter\FilterManager: '@flasher.filter_manager'
    Flasher\Prime\Filter\FilterBuilder: '@flasher.filter_builder'
    Flasher\Prime\Filter\DefaultFilter: '@flasher.filter.default'
    Flasher\Prime\Factory\AbstractFactory: '@flasher.abstract_factory'
    Flasher\Prime\Presenter\AbstractPresenter: '@flasher.abstract_presenter'
    Flasher\Prime\Presenter\Adapter\JsonPresenter: '@flasher.presenter.json'
    Flasher\Prime\Presenter\Adapter\HtmlPresenter: '@flasher.presenter.html'

    flasher.factory_manager: '@flasher'
    Flasher\Prime\FlasherInterface: '@flasher'
    Flasher\Prime\Storage\StorageManagerInterface: '@flasher.storage_manager'
    Flasher\Prime\Renderer\RendererManagerInterface: '@flasher.renderer_manager'
    Flasher\Prime\Presenter\PresenterManagerInterface: '@flasher.presenter_manager'
    Flasher\Prime\Middleware\FlasherBusInterface: '@flasher.flasher_bus'
    Flasher\Prime\Filter\FilterManagerInterface: '@flasher.filter_manager'
    Flasher\Prime\EventDispatcher\EventDispatcherInterface: '@flasher.event_dispatcher'
    Flasher\Prime\Storage\StorageInterface: '@flasher.storage'
