services:
    _defaults:
        public: true

    flasher.config:
        class: Flasher\Prime\Config\Config
        arguments:
            - null

    flasher:
        class: Flasher\Prime\Flasher
        arguments:
            - '@flasher.config'

    flasher.notification_factory:
        class: Flasher\Prime\Factory\NotificationFactory
        arguments:
            - '@flasher.storage_manager'
        tags:
            - { name: 'flasher.factory', alias: 'template' }

    flasher.storage:
        class: Flasher\Symfony\Storage\Storage
        arguments:
            - '@session'

    flasher.storage_manager:
        class: Flasher\Prime\Storage\StorageManager
        arguments:
            - '@flasher.storage'
            - '@flasher.event_dispatcher'

    flasher.filter:
        class: Flasher\Prime\Filter\Filter

    flasher.event_dispatcher:
        class: Flasher\Prime\EventDispatcher\EventDispatcher

    flasher.event_listener.filter_listener:
        class: Flasher\Prime\EventDispatcher\EventListener\FilterListener
        public: false
        arguments:
            - '@flasher.filter'
        tags:
            - { name: 'flasher.event_subscriber' }

    flasher.event_listener.post_flush_listener:
        class: Flasher\Prime\EventDispatcher\EventListener\RemoveListener
        public: false
        tags:
            - { name: 'flasher.event_subscriber' }

    flasher.event_listener.stamps_listener:
        class: Flasher\Prime\EventDispatcher\EventListener\StampsListener
        public: false
        tags:
            - { name: 'flasher.event_subscriber' }

    flasher.event_listener.template_listener:
        class: Flasher\Prime\EventDispatcher\EventListener\TemplateListener
        public: false
        arguments:
            - '@flasher.config'
            - '@flasher.template_engine'
        tags:
            - { name: 'flasher.event_subscriber' }

    flasher.twig.extension:
        class: Flasher\Symfony\Twig\FlasherTwigExtension
        arguments:
            - '@flasher.renderer'
        tags:
            - { name: 'twig.extension' }

    flasher.renderer:
        class: Flasher\Prime\Renderer\Renderer
        arguments:
            - '@flasher.storage_manager'
            - '@flasher.event_dispatcher'
            - '@flasher.config'

    flasher.session_listener:
        class: Flasher\Symfony\EventListener\SessionListener
        arguments:
            - '@flasher.config'
            - '@flasher'
            - '@flasher.renderer'
        tags:
            - { name: 'kernel.event_subscriber' }

    flasher.template_engine:
        class: Flasher\Symfony\Template\TwigEngine
        arguments:
            - '@twig'

    Flasher\Prime\Config\Config: '@flasher.config'
    Flasher\Prime\Flasher: '@flasher'
    Flasher\Prime\Renderer\Renderer: '@flasher.renderer'
    Flasher\Prime\EventDispatcher\EventDispatcher: '@flasher.event_dispatcher'
    Flasher\Symfony\Storage\Storage: '@flasher.storage'
    Flasher\Prime\Storage\StorageManager: '@flasher.storage_manager'
    Flasher\Prime\Filter\Filter: '@flasher.filter'
    Flasher\Prime\Factory\NotificationFactory: '@flasher.notification_factory'
    Flasher\Symfony\Template\TwigEngine: '@flasher.template_engine'

    Flasher\Prime\Config\ConfigInterface: '@flasher.config'
    Flasher\Prime\FlasherInterface: '@flasher'
    Flasher\Prime\Storage\StorageManagerInterface: '@flasher.storage_manager'
    Flasher\Prime\Renderer\RendererInterface: '@flasher.renderer'
    Flasher\Prime\Filter\FilterInterface: '@flasher.filter'
    Flasher\Prime\EventDispatcher\EventDispatcherInterface: '@flasher.event_dispatcher'
    Flasher\Prime\Storage\StorageInterface: '@flasher.storage'
    Flasher\Prime\Factory\NotificationFactoryInterface: '@flasher.notification_factory'
    Flasher\Prime\Template\EngineInterface: '@flasher.template_engine'
