services:
    flasher.config:
        class: Flasher\Prime\Config\Config
        arguments:
            - null

    flasher.abstract_manager:
        class: Flasher\Prime\Manager\AbstractManager
        abstract: true
        arguments:
            - '@flasher.config'

    flasher:
        class: Flasher\Prime\Flasher
        parent: 'flasher.abstract_manager'

    flasher.renderer_manager:
        class: Flasher\Prime\Renderer\RendererManager
        parent: 'flasher.abstract_manager'

    flasher.abstract_factory:
        class: Flasher\Prime\Factory\AbstractFactory
        abstract: true
        arguments:
            - '@flasher.flasher_bus'
