services:
    flasher.console:
        class: Flasher\Console\Prime\FlasherConsole
        arguments:
            - '@flasher.storage_manager'
            - '@flasher.event_dispatcher'
            - []

    flasher.event_listener.render_listener:
        class: Flasher\Console\Prime\EventListener\RenderListener
        public: false
        arguments:
            - '@flasher.console'
        tags:
            - { name: 'flasher.event_subscriber', priority: -256 }

    flasher.console.notify_send:
        class: Flasher\Console\Prime\Notifier\NotifySendNotifier
        public: false
        arguments:
            - []
        tags:
            - { name: 'flasher.console_notifier' }
