name: Split Monorepo

on:
    push:
        branches:
            - main
        tags:
            - '*'

jobs:
    split_monorepo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    - { path: 'src/Prime', repo: 'flasher' }
                    - { path: 'src/Laravel', repo: 'flasher-laravel' }
                    - { path: 'src/Symfony', repo: 'flasher-symfony' }

                    - { path: 'src/Cli/Prime', repo: 'flasher-cli' }
                    - { path: 'src/Cli/Laravel', repo: 'flasher-cli-laravel' }
                    - { path: 'src/Cli/Symfony', repo: 'flasher-cli-symfony' }

                    - { path: 'src/Noty/Prime', repo: 'flasher-noty' }
                    - { path: 'src/Noty/Laravel', repo: 'flasher-noty-laravel' }
                    - { path: 'src/Noty/Symfony', repo: 'flasher-noty-symfony' }

                    - { path: 'src/Notyf/Prime', repo: 'flasher-notyf' }
                    - { path: 'src/Notyf/Laravel', repo: 'flasher-notyf-laravel' }
                    - { path: 'src/Notyf/Symfony', repo: 'flasher-notyf-symfony' }

                    - { path: 'src/Pnotify/Prime', repo: 'flasher-pnotify' }
                    - { path: 'src/Pnotify/Laravel', repo: 'flasher-pnotify-laravel' }
                    - { path: 'src/Pnotify/Symfony', repo: 'flasher-pnotify-symfony' }

                    - { path: 'src/SweetAlert/Prime', repo: 'flasher-sweetalert' }
                    - { path: 'src/SweetAlert/Laravel', repo: 'flasher-sweetalert-laravel' }
                    - { path: 'src/SweetAlert/Symfony', repo: 'flasher-sweetalert-symfony' }

                    - { path: 'src/Toastr/Prime', repo: 'flasher-toastr' }
                    - { path: 'src/Toastr/Laravel', repo: 'flasher-toastr-laravel' }
                    - { path: 'src/Toastr/Symfony', repo: 'flasher-toastr-symfony' }

                    - { path: 'packs/php-pack', repo: 'php-pack' }
                    - { path: 'packs/laravel-pack', repo: 'laravel-pack' }
                    - { path: 'packs/symfony-pack', repo: 'symfony-pack' }

        steps:
            -   uses: actions/checkout@v2

            -   if: "!startsWith(github.ref, 'refs/tags/')"
                name: Monorepo Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@2.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    package-directory: '${{ matrix.package.path }}'
                    split-repository-organization: 'php-flasher'
                    split-repository-name: '${{ matrix.package.repo }}'
                    user-name: "Younes KHOUBZA"
                    user-email: "younes.khoubza@gmail.com"
                    branch: main

            -   if: "startsWith(github.ref, 'refs/tags/')"
                name: Monorepo Tagged Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@2.0
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    package-directory: 'src/${{ matrix.package.path }}'
                    split-repository-organization: 'php-flasher'
                    split-repository-name: '${{ matrix.package.repo }}'
                    user-name: "Younes KHOUBZA"
                    user-email: "younes.khoubza@gmail.com"
                    branch: main
